### ISSUE TITLE
What is this program doing?

### ISSUE THREAD

**Issue by SMASTER4** [Altomixik/cabbage#1]
Excuse me, but I am not quite sure what this repository is supposed to be doing. It seems to me like some library for a compiler or interpreter for a programming language, am I right? I am quite interested on what this programming language/repository called cabbage has to offer since I am looking for a more... let's say "elegant" alternative to C. It would be really nice of you if you could give me more information.

**Comment by Altomixik** [comment]
Right now, you are digging in a total stranger's code, one that you will never see, or hear. One that might be on the other side of earth. Why then tumble the old unfinished bookshelf of abandoned projects that belong to that person? 

This is an old abandoned project of mine.
